//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wtc_3_forms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wtc_3_forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///&lt;!--
        ///span.cls_003{font-family:Arial,serif;font-size:20.1px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}
        ///div.cls_003{font-family:Arial,serif;font-size:20.1px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}
        ///span.cls_002{font-family:Arial,serif;font-size:20.1px;color:rgb(153,153,153);font-weight:bold;font-style:normal;text-decoration: none}
        ///div.c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string iris_html {
            get {
                return ResourceManager.GetString("iris_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iris_pdf {
            get {
                object obj = ResourceManager.GetObject("iris_pdf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1250\deff0\nouicompat\deflang1038{\fonttbl{\f0\fswiss\fcharset0 Arial;}{\f1\froman\fcharset0 Times New Roman;}{\f2\fnil\fcharset0 Agency FB;}{\f3\fnil\fcharset0 Calibri;}{\f4\fnil\fcharset2 Symbol;}}
        ///{\colortbl ;\red0\green0\blue0;\red154\green154\blue154;\red255\green0\blue0;\red255\green255\blue0;\red205\green205\blue205;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\cf1\b\f0\fs40\lang14 E-Radius Kft. \cf2 Jelenl\&apos;e9ti \&apos;edv\par
        ///
        ///\pard{\pntext\f4\&apos;B7\tab}{\*\pn\pnlvlblt\pn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string iris_rtf {
            get {
                return ResourceManager.GetString("iris_rtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Radius Kft. Jelenléti ív
        ///Fizetési idoszak:
        ///Alkalmazott:
        ///Felettes:
        ///Nap Munkaórák
        ///száma
        ///Túlóra
        ///(óra)
        ///Betegszabadság
        ///(nap)
        ///Radics Márton
        ///2018-08-01 2018-08-31
        ///Szabadság
        ///(nap)
        ///-
        ///Készenlét
        ///(óra)
        ///Burián Imre
        ///Home Office
        ///(nap)
        ///Kiküldetés
        ///(nap)
        ///Szerda 2018-08-01 08:00 - 16:30 8 Normal
        ///Csütörtök 2018-08-02 07:14 - 15:49 8
        ///Péntek 2018-08-03 07:42 - 16:09 8
        ///Szombat 2018-08-04 true
        ///Vasárnap 2018-08-05 true
        ///Hétfo 2018-08-06 07:24 - 16:10 8
        ///Kedd 2018-08-07 06:23 - 17:46 8
        ///Szerda 2018-08-08  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string iris_txt {
            get {
                return ResourceManager.GetString("iris_txt", resourceCulture);
            }
        }
    }
}
